version: '3.9'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=vegefoods
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Admin  
  web:
    build: .
    entrypoint: sh docker-entrypoint.sh
    # command: python manage.py runserver 0.0.0.0:8100
    volumes:
      - .:/code
    ports:
      - "8100:8100"
    depends_on:
      - db

