# Generated by Django 2.2.14 on 2020-12-24 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190630_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('A', 'All'), ('V', 'Vegetables'), ('F', 'Fruits'), ('J', 'Juice'), ('D', 'Dried')], max_length=2),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('EL', 'Extra Large')], max_length=1),
        ),
    ]
