# Generated by Django 2.2.14 on 2020-12-24 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201224_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
